// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:meihua/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(Db64guaAdapter());
    registerAdapter(Db8guaAdapter());
    registerAdapter(DbConfigAdapter());
    registerAdapter(DbHistoryAdapter());
    registerAdapter(DbHistorySyncAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(Db64guaAdapter());
    registerAdapter(Db8guaAdapter());
    registerAdapter(DbConfigAdapter());
    registerAdapter(DbHistoryAdapter());
    registerAdapter(DbHistorySyncAdapter());
  }
}
